//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int IDUSUARIO { get; set; }
        public string NOMBRE_APELLIDO { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<System.DateTime> ULTIMO_LOGIN { get; set; }
        public Nullable<int> ID_ROL { get; set; }
    
        public virtual ROLES ROLES { get; set; }
    }
}
