--Scripts de parametrizacion de las 2 tablas
USE EjercicioApi
INSERT INTO ROLES (IDROL,ROL) VALUES (1,'ADMINISTRADOR')
INSERT INTO ROLES (IDROL,ROL) VALUES (2,'USUARIO')
INSERT INTO ROLES (IDROL,ROL) VALUES (3,'CONSULTA')

USE EjercicioApi
INSERT INTO USUARIOS (IDUSUARIO,NOMBRE_APELLIDO,USUARIO,PASSWORD,ACTIVO, ULTIMO_LOGIN,ID_ROL)
VALUES
(1,'ALE','USER1','USER123',1,GETDATE(),1)
INSERT INTO USUARIOS (IDUSUARIO,NOMBRE_APELLIDO,USUARIO,PASSWORD,ACTIVO, ULTIMO_LOGIN,ID_ROL)
VALUES
(2,'PEPE','USER2','USER124',1,GETDATE(),1)
